#!/bin/bash
qsub small_shell_niche.sh 1 1
qsub small_shell_niche.sh 1 2
qsub small_shell_niche.sh 1 3
qsub small_shell_niche.sh 1 4
qsub small_shell_niche.sh 1 5
qsub small_shell_niche.sh 1 6
qsub small_shell_niche.sh 1 7
qsub small_shell_niche.sh 1 8
qsub small_shell_niche.sh 1 9
qsub small_shell_niche.sh 1 10
qsub small_shell_niche.sh 1 11
qsub small_shell_niche.sh 1 12
qsub small_shell_niche.sh 1 13
qsub small_shell_niche.sh 1 14
qsub small_shell_niche.sh 1 15
qsub small_shell_niche.sh 1 16
qsub small_shell_niche.sh 1 17
qsub small_shell_niche.sh 1 18
qsub small_shell_niche.sh 2 1
qsub small_shell_niche.sh 2 2
qsub small_shell_niche.sh 2 3
qsub small_shell_niche.sh 2 4
qsub small_shell_niche.sh 2 5
qsub small_shell_niche.sh 2 6
qsub small_shell_niche.sh 2 7
qsub small_shell_niche.sh 2 8
qsub small_shell_niche.sh 2 9
qsub small_shell_niche.sh 2 10
qsub small_shell_niche.sh 2 11
qsub small_shell_niche.sh 2 12
qsub small_shell_niche.sh 2 13
qsub small_shell_niche.sh 2 14
qsub small_shell_niche.sh 2 15
qsub small_shell_niche.sh 2 16
qsub small_shell_niche.sh 2 17
qsub small_shell_niche.sh 2 18
qsub small_shell_niche.sh 3 1
qsub small_shell_niche.sh 3 2
qsub small_shell_niche.sh 3 3
qsub small_shell_niche.sh 3 4
qsub small_shell_niche.sh 3 5
qsub small_shell_niche.sh 3 6
qsub small_shell_niche.sh 3 7
qsub small_shell_niche.sh 3 8
qsub small_shell_niche.sh 3 9
qsub small_shell_niche.sh 3 10
qsub small_shell_niche.sh 3 11
qsub small_shell_niche.sh 3 12
qsub small_shell_niche.sh 3 13
qsub small_shell_niche.sh 3 14
qsub small_shell_niche.sh 3 15
qsub small_shell_niche.sh 3 16
qsub small_shell_niche.sh 3 17
qsub small_shell_niche.sh 3 18
